@hostname = https://ace.acrm.accessacloud.com
@apiPath = /rest/v10
@api = {{ hostname }}{{ apiPath }}

### Get list of methods

GET {{ api }}/help HTTP/1.1

### Auth Method
# @name authRequest
POST {{ api }}/oauth2/token
content-type: application/json

{
    "grant_type":"password",
    "client_id": "sugar",
    "username": "{{ crmUsername }}",
    "password": "{{ crmPassword }}",
    "platform": "custom-crm-connector"
}

### Get contacts (only 20)

GET {{ api }}/Contacts?max_num=999999
Authorization: Bearer {{ authRequest.response.body.access_token }}

### Get events (only 20)

GET {{ api }}/cours_Event?max_num=999999
Authorization: Bearer {{ authRequest.response.body.access_token }}

### Get eventsattendances (only 20)

GET {{ api }}/cours_EventAttendance?max_num=999999
Authorization: Bearer {{ authRequest.response.body.access_token }}



### Filter contacts by email, with results
@emailToFind = testing-api-7628537@gavinhenderson.co.uk

GET {{ api }}/Contacts
    ?filter=[{"email": "{{ emailToFind }}" }]
Authorization: Bearer {{ authRequest.response.body.access_token }}


### Filter contacts by email, no results

GET {{ api }}/Contacts
    ?filter=[{"email":"totallymadeup"}]
Authorization: Bearer {{ authRequest.response.body.access_token }}

### Create Contact
@randomEmail = testing-api-{{ $randomInt 0 9999999 }}@gavinhenderson.co.uk
POST {{ api }}/Contacts
Authorization: Bearer {{ authRequest.response.body.access_token }}
content-type: application/json

{
    "email1": "{{ randomEmail }}",
    "first_name": "{{ randomEmail }}",
    "last_name": "Unknown",
    "receives_newsletter_c": false
}

### Create event attendence
POST {{ api }}/cours_EventAttendance
Authorization: Bearer {{ authRequest.response.body.access_token }}
content-type: application/json

{
    "name": "temp test",
    "cours_eventattendance_contacts": {
        "add": ["0bd2f8e8-7a36-11ed-8822-00163ecfc8ed"]
    },
    "cours_event_cours_eventattendance": {
        "add": ["3df50498-507d-11ed-988e-00163ecfc8ed"]
    }
}

### Switch contact to recieve newsletter
@idToSubscribe = da95208e-69ab-11ed-ae8a-00163ecfc8ed
PUT {{ api }}/Contacts/{{ idToSubscribe }}
Authorization: Bearer {{ authRequest.response.body.access_token }}
content-type: application/json

{
    "receives_newsletter_c": true
}

### Request to DO 

POST https://crm-connector-k7gic.ondigitalocean.app/crm/crm-functions
Content-Type: application/json

{
    "email": "123@gavinhenderson.co.uk",
    "method": "add-to-newsletter",
    "location": "rest"
}

### Request to DO 

POST https://crm-connector-k7gic.ondigitalocean.app/crm/crm-functions
Content-Type: application/json

{
    "email":"gavin.henderson@hotmail.co.uk",
    "eventSlug": "developing-and-using-a-communication-book-i-10th-jan-23",
    "method": "add-to-course"
}