packages:
  - name: sample
    actions:
      - name: hello
        runtime: "nodejs:default"

  - name: crm
    actions:
      - name: create-contact-from-email
        environment:
          SERVER_URL: "${SERVER_URL}"
        runtime: "nodejs:default"
