packages:
  - name: crm
    environment:
      CRM_USERNAME: "${CRM_USERNAME}"
      CRM_PASSWORD: "${CRM_PASSWORD}"
      SLACK_TOKEN: "${SLACK_TOKEN}"
      SLACK_SIGNING_TOKEN: "${SLACK_SIGNING_TOKEN}"
      SEND_SUCCESS: "${SEND_SUCCESS}"
    actions:
      - name: crm-functions
        runtime: "nodejs:default"
        limits:
          timeout: 120000
          memory: 256
